### DISCUSSION TITLE
Curious how you get your ZSH prompt to show how nested you are in environments?

### DISCUSSION THREAD

**Discussion by createchange** [wincent/wincent#144] [General]
From watching your video on profiling ZSH startup times, I noticed that, as you were dropping into new shells, the `>` part of the prompt was showing precisely how far nested you were in shells. I did some looking through your .zshrc, but nothing caught my eye as pertains to this. I was hoping you could let me know as I would love to replicate that!

**Comment by wincent** [comment]
Hi @createchange 👋🏻 

The `$SHLVL` variable tells you how many levels deep you are.

- In my `.tmux.conf`, [I tell tmux to always start at level 1](https://github.com/wincent/wincent/blob/641f3dbf2be04f04562c7611afb73a48d87274d4/aspects/dotfiles/files/.config/tmux/tmux.conf#L147-L148).
- I have [some logic](https://github.com/wincent/wincent/blob/641f3dbf2be04f04562c7611afb73a48d87274d4/aspects/dotfiles/files/.zshrc#L368-L379) to adjust it depending on things like platform, putting the calculated value in `$LVL`.
- And then in [this line](https://github.com/wincent/wincent/blob/641f3dbf2be04f04562c7611afb73a48d87274d4/aspects/dotfiles/files/.zshrc#L395) you can see it being used. I don't blame you for not finding this 🤣 — the bit that matters is this: `$(printf '\u276f%.0s' {1..$LVL})`, which prints one unicode `\u276f` character (`❯`) per level.
- The other bits are [kind of explained in comments](https://github.com/wincent/wincent/blob/641f3dbf2be04f04562c7611afb73a48d87274d4/aspects/dotfiles/files/.zshrc#L381-L390), or you could paste it into ChatGPT or ask Copilot to explain it 😁.

**Reply by createchange** [reply]
Ah ha! Thanks for sending me down the right path. You're a wizard!

As an aside, very related note... because I am not a wizard, I have been using starship to enhance my shell, and realized that they have a native implementation for this:

```toml
format = "$all$directory$shlvl$character"
right_format = "$battery"

[character]
success_symbol = "[❯](bold green) "
error_symbol = "[❯](bold red) "

[shlvl]
disabled = false
format = '[$symbol]($style)'
repeat = true
symbol = '❯'
repeat_offset = 1
threshold = 2
```

<img width="413" alt="image" src="https://github.com/wincent/wincent/assets/29058450/5ee1f732-3858-4d3a-bf78-a41a3f8b4afe">
